package OpenStack::MetaAPI::UserAgent;

use strict;
use warnings;

use parent 'LWP::UserAgent';

# ABSTRACT: an LWP::UserAgent that leaves TLS hostname verification to LWP

# VERSION: generated by DZP::OurPkgVersion

sub new {
    my ($class, %opts) = @_;

    # A copy, so that the caller's hash keeps what it passed.
    my %ssl_opts = %{$opts{ssl_opts} // {}};
    delete $ssl_opts{verify_hostname};
    $opts{ssl_opts} = \%ssl_opts;

    return $class->SUPER::new(%opts);
}

1;

__END__

=head1 SYNOPSIS

    # OpenStack::MetaAPI uses this class unless you name another one.
    my $api = OpenStack::MetaAPI->new($endpoint, %auth_args);

    # An auth object that you build yourself has to be given it.
    my $auth = OpenStack::Client::Auth->new(
        $endpoint, %auth_args,
        package_ua => 'OpenStack::MetaAPI::UserAgent',
    );
    my $api = OpenStack::MetaAPI->new({auth => $auth});

=head1 DESCRIPTION

L<OpenStack::Client> makes each of its user agents with

    ssl_opts => { verify_hostname => 0 }

and no argument changes that.  So without this class, every request goes to
whichever server answers for the endpoint, with the C<X-Auth-Token> of the
session in its headers.

This class removes C<verify_hostname> from the C<ssl_opts> it is given, and
passes everything else to L<LWP::UserAgent>.  LWP then decides, as it does for
any user agent: the check is on, unless the environment variable
C<PERL_LWP_SSL_VERIFY_HOSTNAME> is set to 0.  To trust a private certificate
authority, set C<PERL_LWP_SSL_CA_FILE> or C<PERL_LWP_SSL_CA_PATH>.  To change
anything else, subclass this class and give yours as C<package_ua>.

=head1 METHODS

=head2 new( %opts )

Returns a new user agent, as L<LWP::UserAgent/new> does, from C<%opts> with
C<verify_hostname> taken out of C<ssl_opts>.

=cut
